In [31]:
import numpy as np

In [32]:
a=np.random.randint(1,20,5)
a

array([ 8,  8, 11, 11, 14])

In [33]:
a.reshape(1,-1) #Row vector

array([[ 8,  8, 11, 11, 14]])

In [34]:
a.reshape(-1,1) #Column vector

array([[ 8],
       [ 8],
       [11],
       [11],
       [14]])

In [35]:
a[:,np.newaxis]

array([[ 8],
       [ 8],
       [11],
       [11],
       [14]])

In [36]:
print(a.shape)

(5,)


In [37]:
a[np.newaxis,:]

array([[ 8,  8, 11, 11, 14]])

In [38]:
print(a.shape)

(5,)


### merge

In [39]:
s1 = np.random.randint(1,20,25).reshape(5,5)
s2 = np.random.randint(10,30,40).reshape(-1,5)

In [40]:
s1

array([[18,  6, 16,  4, 15],
       [15,  2, 18,  9, 16],
       [ 7, 13,  1, 15, 13],
       [16,  1, 14, 12,  4],
       [ 7, 13, 11,  1,  9]])

In [41]:
s2

array([[24, 18, 16, 16, 29],
       [17, 14, 13, 19, 26],
       [16, 13, 16, 27, 20],
       [19, 19, 18, 13, 11],
       [10, 19, 29, 10, 25],
       [18, 28, 21, 25, 19],
       [10, 13, 25, 10, 18],
       [11, 13, 14, 12, 16]])

In [45]:
x = np.arange(0,15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])